export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const DOWNLOAD_PRODUCT = "DOWNLOAD_PRODUCT";
export const DOWNLOAD_PRODUCT_SUCCESS = "DOWNLOAD_PRODUCT_SUCCESS";
export const DOWNLOAD_PRODUCT_ERROR = "DOWNLOAD_PRODUCT_ERROR";

export const GET_PRODUCT_DELETED = "GET_PRODUCT_DELETED";
export const PRODUCT_DELETED_SUCCESS = "PRODUCT_DELETED_SUCCESS";
export const PRODUCT_DELETED_ERROR = "PRODUCT_DELETED_ERROR";

export const GET_PRODUCT_EDIT = "GET_PRODUCT_EDIT";
export const START_PRODUCT_EDIT = "START_PRODUCT_EDIT";
export const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS";
export const PRODUCT_EDIT_ERROR = "PRODUCT_EDIT_ERROR";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";